# Generated by Django 4.2.2 on 2023-06-30 15:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_tag_posts_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 15, 9, 16, 616634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.category'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 15, 9, 16, 617099, tzinfo=datetime.timezone.utc)),
        ),
    ]
