# Generated by Django 4.2.2 on 2023-07-03 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_category_date_created_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='image', upload_to='imgs/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 18, 9, 31, 672670, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tag',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 3, 18, 9, 31, 673034, tzinfo=datetime.timezone.utc)),
        ),
    ]
